### ISSUE TITLE
two livox horizon lidar calibration

### ISSUE THREAD

**Issue by DannyRaspect** [Tomato1107/multi_livox_lidar_calibration#1]
你好
我有兩個關於代碼的問題, 我也遇到了你關於frame_id的問題

首先，與原來的相比，你的代碼做了什麼修改

第二，如果我想在我的激光雷達上使用你修改過的代碼，我應該在代碼中修改什麼適應我的激光雷達 (livox horizon) 

你能分享你的經驗嗎?

**Comment by Tomato1107** [comment]
> 你好 我有兩個關於代碼的問題, 我也遇到了你關於frame_id的問題
> 
> 首先，與原來的相比，你的代碼做了什麼修改
> 
> 第二，如果我想在我的激光雷達上使用你修改過的代碼，我應該在代碼中修改什麼適應我的激光雷達 (livox horizon)
> 
> 你能分享你的經驗嗎?

1.  增加了第107行的代码，避免frame_id冲突。修改了multi_lidar_calibrator.launch中第2，3行的topic名字，在rviz中需要对应修改你自己的livox的名字。如果不收敛，需要调整cfg文件夹里面child_topic_list的第2行待校正的lidar的初始位姿的数值，比如调整角度和位置（可用不收敛的tf数值，改变需要调整的角度方向，或者xyz的正负号）。可以查看，我其实在视频里面已经调整过了初始位姿，所以收敛比较快，一开始数字我都给0，怎么运行都不收敛。
2.  需要在multi_lidar_calibrator.launch中和rviz中修改你自己的2个lidar对应的名字。如有需要，可以调整cfg文件夹里面child_topic_list的第3行待校正的激光雷达的初始位姿的数值。lidar数量多于2个的情况，操作只需要换掉待标定的lidar的名字

**Comment by DannyRaspect** [comment]
我想問更多關於那你怎麼樣判斷我們得到的外參的準確度和精度是優秀的還是一般的,可以顯示更多詳細信息有關您的結果. Thank you.

**Comment by Tomato1107** [comment]
> 我想問更多關於那你怎麼樣判斷我們得到的外參的準確度和精度是優秀的還是一般的,可以顯示更多詳細信息有關您的結果. Thank you.

我是通过白色的点云与目标点云重合来判断的，关于精度与准确度需要调整代码里面的参数吧。

**Comment by DannyRaspect** [comment]
我想知道更多關於你的testing  rosbag 的細節，因為當我使用自己的 rosbag 時我得到了不好的結果

首先，你有沒有在 rosbag 記錄之前 校準 livox 內置 IMU (built-in IMU)

二、你是 手持激光雷達 還是 把激光雷達裝在車上，我是怕車輛的震動會影響livox內置的IMU

三，你是使用livox_viewer進行數據記錄, 獲取.lvx然後改變到.bag文件，還是使用livox_driver_ros & rosbag record -a 在terminal 記錄數據

最後，如果方便的話可以和我分享一下你的 rosbag for my reference

**Comment by Tomato1107** [comment]
我是手持场景，校正lidar没有用imu，还有实际2个lidar间角度较大的时候，或者重合区域不多的话效果并不好。
我是直接用的livox_ros_driver里面的pointcloud2的格式。
在车上用的场景我了解还不是很多，可能边跑图边校正会好一些。现在我的两个lidar相隔的很近，重合角度也比较大

**Comment by DannyRaspect** [comment]
好的了解!

如果我需要校準四個激光雷達，如何修改 tf.launch

例如，除了外部參數，我應該修改參數後面的frame_ id (/livox_frame /livox_child 10)，還是每個激光雷達的 (/livox_frame /livox_child 10) 相同

lidar1:  node pkg="tf" type="static_transform_publisher" name="fl_fh" args="-4.17355 -0.10968 -1.23994  2.03452  1.25031 -2.07277 /livox_frame /livox_child 10"

lidar2: node pkg="tf" type="static_transform_publisher" name="lf_fh" args="-0.8764  -0.04563 4.8657 2.03452  0.09872 5.980234 /livox_frame /livox_child 10"

**Comment by Tomato1107** [comment]
> 好的了解!
> 
> 如果我需要校準四個激光雷達，如何修改 tf.launch
> 
> 例如，除了外部參數，我應該修改參數後面的frame_ id (/livox_frame /livox_child 10)，還是每個激光雷達的 (/livox_frame /livox_child 10) 相同
> 
> lidar1: node pkg="tf" type="static_transform_publisher" name="fl_fh" args="-4.17355 -0.10968 -1.23994 2.03452 1.25031 -2.07277 /livox_frame /livox_child 10"
> 
> lidar2: node pkg="tf" type="static_transform_publisher" name="lf_fh" args="-0.8764 -0.04563 4.8657 2.03452 0.09872 5.980234 /livox_frame /livox_child 10"

tf的用法我还不是很熟悉，目前我还没有用到tf.lanuch。
可以多多尝试，因为我也还是新入门。
我用livox_viewer手动调整得出数据很接近

**Comment by Tomato1107** [comment]
> 好的了解!
> 
> 如果我需要校準四個激光雷達，如何修改 tf.launch
> 
> 例如，除了外部參數，我應該修改參數後面的frame_ id (/livox_frame /livox_child 10)，還是每個激光雷達的 (/livox_frame /livox_child 10) 相同
> 
> lidar1: node pkg="tf" type="static_transform_publisher" name="fl_fh" args="-4.17355 -0.10968 -1.23994 2.03452 1.25031 -2.07277 /livox_frame /livox_child 10"
> 
> lidar2: node pkg="tf" type="static_transform_publisher" name="lf_fh" args="-0.8764 -0.04563 4.8657 2.03452 0.09872 5.980234 /livox_frame /livox_child 10"

车上的场景可以了解一下下面的算法，看起来很不错
https://github.com/hku-mars/decentralized_loam
https://github.com/hku-mars/mlcc

**Comment by DannyRaspect** [comment]
謝謝你的建議，我試過mlcc，但是太難用了。我想通過硬件部分設計來最小化振動效應。

還有一件事是，我在運行 multi_lidar_calibrator.launch 後得到的 tf 值應該是一組參數，它與我們放入 child_topic_list 的initial外部參數略有不同，這是更準確的結果，對吧？

但我的 tf 結果與初始的外部參數完全不同。你對此有什麼想法嗎？

such as,
(1)
initial extrinsic ( from livox_viewer) : 0.107736  -0.122713  0.201322  **94.1414 (yaw)**  179.151 -179.317

tf result ( running multi_lidar_calibrator.launch ): -0.0167887  0.0191225 -0.0313723  **3.03522(yaw)** -0.0802186  -0.24622

(2)

initial extrinsic ( from livox_viewer): -3.44383  -1.95834  -1.05285  **100.004 (yaw)**  7.83738  3.81332

tf result ( running multi_lidar_calibrator.launch ): -3.44383 -1.95834 -1.05285   **2.61463 (yaw)**   1.5874  0.671727

remark: 實際上yaw應該大

**Comment by Tomato1107** [comment]
> 謝謝你的建議，我試過mlcc，但是太難用了。我想通過硬件部分設計來最小化振動效應。
> 
> 還有一件事是，我在運行 multi_lidar_calibrator.launch 後得到的 tf 值應該是一組參數，它與我們放入 child_topic_list 的initial外部參數略有不同，這是更準確的結果，對吧？
> 
> 但我的 tf 結果與初始的外部參數完全不同。你對此有什麼想法嗎？
> 
> such as, (1) initial extrinsic ( from livox_viewer) : 0.107736 -0.122713 0.201322 **94.1414 (yaw)** 179.151 -179.317
> 
> tf result ( running multi_lidar_calibrator.launch ): -0.0167887 0.0191225 -0.0313723 **3.03522(yaw)** -0.0802186 -0.24622
> 
> (2)
> 
> initial extrinsic ( from livox_viewer): -3.44383 -1.95834 -1.05285 **100.004 (yaw)** 7.83738 3.81332
> 
> tf result ( running multi_lidar_calibrator.launch ): -3.44383 -1.95834 -1.05285 **2.61463 (yaw)** 1.5874 0.671727
> 
> remark: 實際上yaw應該大

单位不一样，一个是度，一个是弧度，需要转换一下

**Comment by Tomato1107** [comment]
需要用running multi_lidar_calibrator.launch点云重合后生成的tf，实际我用的还是livox_viewer手动调整的结果
livox_viewer里面是否有清除上一次存留的结果

**Comment by Tomato1107** [comment]
Thanks
